"""add description

Revision ID: c0bf031a093b
Revises: add_initial_data
Create Date: 2026-05-03 22:55:00.132877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bf031a093b'
down_revision: Union[str, Sequence[str], None] = 'add_initial_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=100), nullable=False, server_default='None'))
    op.alter_column('products', 'price',
                existing_type=sa.REAL(),
                type_=sa.Float(precision=3),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
                existing_type=sa.Float(precision=3),
                type_=sa.REAL(),
                existing_nullable=False)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
